org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=128M -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.java.home=C:/src/jdk-17.0.16+8

# Active le démon Gradle pour un démarrage plus rapide
org.gradle.daemon=true

# Permet l'exécution parallèle sur les modules indépendants
org.gradle.parallel=true

# Active la mise en cache pour réutiliser les sorties de build intermédiaires
org.gradle.caching=true

# Désactiver le cache de configuration moderne pour éviter l'erreur avec DebugMinSdkCheck
org.gradle.configuration-cache=false