// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cjtiRN9JCkmcvoyym6Rad_9YxgVj4OU',
    appId: '1:60771248934:web:9b262c5dc6a7e669a82fe7',
    messagingSenderId: '60771248934',
    projectId: 'transport-intelligent-ia',
    authDomain: 'transport-intelligent-ia.firebaseapp.com',
    storageBucket: 'transport-intelligent-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUDgopszTDY1KONS-I6ZG3gSSgOJIk8M',
    appId: '1:60771248934:android:aba026d148c110f4a82fe7',
    messagingSenderId: '60771248934',
    projectId: 'transport-intelligent-ia',
    storageBucket: 'transport-intelligent-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAA5cL_7sMXv3XRyraie5SmYwWnUm5A1w',
    appId: '1:60771248934:ios:52b593ad0fa9c0d5a82fe7',
    messagingSenderId: '60771248934',
    projectId: 'transport-intelligent-ia',
    storageBucket: 'transport-intelligent-ia.firebasestorage.app',
    iosBundleId: 'com.joan.updateCamtrans',
  );
}
